### ISSUE TITLE
Inaccurate description

### ISSUE THREAD

**Issue by rjlatail** [learn-co-curriculum/dsc-pandas-groupby#2]
## Link to Canvas

https://learning.flatironschool.com/courses/7244/pages/pandas-groupby?module_item_id=657906

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

### Concern

![Screenshot 2024-02-29 172406](https://github.com/learn-co-curriculum/dsc-pandas-groupby/assets/120394045/df334194-88b2-4580-8648-236afedd5a3f)

In the very last code cell, you include code to return the 1 index (i.e. the second row, which is for 2nd class tickets).  But in the markdown cell immediately after, you state that your example returns results for a 1st class ticket.

## (Optional) Proposed Solution

You can either update the markdown cell with the correct description, or update the code cell to call a string instead of an index:

grouped['female']['1']

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you. We shall take a look.

**Comment by danielburdeno** [comment]
fixed to showcase string label and/or python 0 index. Also added .agg() example
